### ISSUE TITLE
setspeed / setvoltage commands overruled by CO2 sensor

### ISSUE THREAD

**Issue by LaTrappe** [eelcohn/nRF905-API#16]
Hi,

First of all: many thanks for this bloody brilliant piece of work. I had the antenna's laying around for 3 years already but I was lacking all knowledge you luckally posses. 

I notice this on the on other forums as well, but since i don't have a logging there I took the freedom of reporting the bug here. 

I have a Zehnder Co2 sensor in the living room, which overrules the calls to setspeed and setvoltage. The ventilator responds but a few seconds later it will go back to auto. Only way to keep the ventilator running is using the parameters. 

Would be happy to use the setvoltage with a slider bar in Home Assistant.

**Comment by eelcohn** [comment]
I've been contacted by another tweaker who has found a solution for this. I'll implement it in v1.0.1.

I'm the mean time you should be able to set it manually by using the /api/v1/send.json API with the following payloads:

Timer 30 minutes:
```
010016xxFA0302041E00000000000000
```
Set fan to auto CO2 mode
```
010016xxFA0302040000000000000000
```
You'll need to replace the xx with the device id of your nRF905 API controller. You can look that up on the status page at /api/v1/status.json

Please let me know if this temporary fix works for you!

**Comment by Melkboertje** [comment]
Hi,

I am facing the same issue and tested the workaround.
The payload to set the fan to auto is not correct, it sets the fan to max.
The correct payload should be: 

010016xxFA0302000000000000000000

instead of:

010016xxFA0302040000000000000000

**Comment by LaTrappe** [comment]
Hi eelcohn,

Yes this works for me. Looking forward to the 1.0.1
