### ISSUE TITLE
Warning: hardware error while configuring the nRF905

### ISSUE THREAD

**Issue by arjan-s** [eelcohn/nRF905-API#24]
Hi,

I have a `BUVA BoxStream RF+` I would like to control using your API. For this project I bought off AliExpress a [`V2 Nodemcu-CP2102 (ESP8266 ESP-12E)`](https://nl.aliexpress.com/item/32665100123.html) and [`Wavgat NRF905`](https://nl.aliexpress.com/item/4000587179835.html). Yes, I know these aren't the exact types you advise, but I took my chances due to the cost difference. Perhaps the hardware is the reason for my trouble, please let me know if that is the case.

I succeeded following the steps for building the hardware and programming the nRF905 API software to the NodeMCU. The configuration wizard was successful up until the fan discovery wizard. I unplugged the fan unit and plugged it back in, after which the wizard should say "Your fan is successfully configured". However, I got the message "Warning: hardware error while configuring the nRF90".

And indeed, after rebooting the NodeMCU, it connects to my configured WiFi, but the configuration wizard starts again when I open the page.

Please let me know if there is something I can change or do or try, or if I should just buy other boards. :)

**Comment by JoooostB** [comment]
@arjan-s Did you manage to fix your issue?

**Comment by arjan-s** [comment]
No, sadly I wasn't successful with any approach. In the end I replaced the box this year because it was getting old. I now have an Itho Daalderop box hat can be easily controlled with https://github.com/arjenhiemstra/ithowifi
