### ISSUE TITLE
buying module in the netherlands

### ISSUE THREAD

**Issue by remb0** [eelcohn/nRF905-API#25]
Where can I find the best module for my buva box? 
I see 3 versions, with comments not tested or other remarks,  So I'm not sure which one is the best for me and can be bought in the Netherlands.

or are there plans to sell these sets, so we can also contribute in a financial way to this project?

**Comment by nicandris** [comment]
I got the nrf905 from Aliexpress almost a couple of years ago,  `WAVGAT NRF905 Wireless Transceiver Module Wireless Transmitter Receiver Board NF905SE With Antenna FSK GMSK 433 868 915 MHz` I had a few NodeMCUs laying around, but you can get those anywhere (eg amazon or ali again)

**Comment by remb0** [comment]
Can be closed.  Bought at amazon and already received. :)
