### ISSUE TITLE
error verifying sketch

### ISSUE THREAD

**Issue by remb0** [eelcohn/nRF905-API#26]
I bought a nodemcu and de nfr followed the steps but got errors and don't know how to resolve. What's wrong? What do I miss?

I see also a folder on this github: homeassistant. is that a option to flash it with esphome or something?
`
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o: in function `esp8266webserver::ESP8266WebServerTemplate<WiFiServer>::handleClient()':
C:\Users\remco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:368: undefined reference to `server'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x94): undefined reference to `json_sendNotFound()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xbc): undefined reference to `Board::setOnBoardLED(bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xc0): undefined reference to `Board::setADCtoVccMode()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xc4): undefined reference to `nRF905::init(unsigned int, unsigned int, bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xc8): undefined reference to `nRF905::setModeIdle()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xcc): undefined reference to `Board::set_hostname(char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xd0): undefined reference to `htmlAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xd4): undefined reference to `htmlConfigWizardAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xd8): undefined reference to `javascriptAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xdc): undefined reference to `stylesheetAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xe0): undefined reference to `iconsAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xe4): undefined reference to `nRF905::setModePowerDown()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xe8): undefined reference to `Board::deepSleep(unsigned long long)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xec): undefined reference to `Board::enable_IPv6()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xf0): undefined reference to `Board::get_localIPv6()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xf4): undefined reference to `apiv1_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xf8): undefined reference to `apiv2_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0xfc): undefined reference to `apitest_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x100): undefined reference to `nRF905::getMode()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x104): undefined reference to `nRF905::setModeReceive()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x108): undefined reference to `Board::getOnBoardLED()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x12e): undefined reference to `Board::setOnBoardLED(bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x136): undefined reference to `Board::setADCtoVccMode()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x16a): undefined reference to `nRF905::init(unsigned int, unsigned int, bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x18a): undefined reference to `nRF905::setModeIdle()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x1d5): undefined reference to `Board::set_hostname(char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:(.text.setup+0x21f): undefined reference to `Board::setOnBoardLED(bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o: in function `setup':
C:\Users\remco\Documents\Arduino\itho/itho.ino:77: undefined reference to `htmlAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:77: undefined reference to `htmlConfigWizardAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:77: undefined reference to `javascriptAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:78: undefined reference to `stylesheetAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:80: undefined reference to `iconsAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:87: undefined reference to `nRF905::setModePowerDown()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:88: undefined reference to `Board::deepSleep(unsigned long long)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:97: undefined reference to `Board::setOnBoardLED(bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:105: undefined reference to `Board::enable_IPv6()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:106: undefined reference to `Board::get_localIPv6()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:114: undefined reference to `htmlAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:115: undefined reference to `htmlConfigWizardAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:115: undefined reference to `javascriptAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:115: undefined reference to `stylesheetAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:118: undefined reference to `apiv1_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:118: undefined reference to `apiv2_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:119: undefined reference to `apitest_AddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:121: undefined reference to `iconsAddHandlers()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:128: undefined reference to `nRF905::getMode()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:134: undefined reference to `nRF905::setModeReceive()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:136: undefined reference to `nRF905::getMode()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:139: undefined reference to `Board::getOnBoardLED()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:140: undefined reference to `Board::setOnBoardLED(bool)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\itho/itho.ino:150: undefined reference to `nRF905::update()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o: in function `loop':
C:\Users\remco\Documents\Arduino\itho/itho.ino:150: undefined reference to `nRF905::update()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:C:\Users\remco\Documents\Arduino\itho/itho.ino:154: undefined reference to `Board::Board()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o:C:\Users\remco\Documents\Arduino\itho/itho.ino:154: undefined reference to `nRF905::nRF905(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o: in function `setup':
C:\Users\remco\Documents\Arduino\itho/itho.ino:156: undefined reference to `Board::Board()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\itho.ino.cpp.o: in function `_GLOBAL__sub_I_dnsServer':
c:\users\remco\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2/functional:2437: undefined reference to `nRF905::nRF905(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x18): undefined reference to `Board::ReadNVRAM(unsigned char*, unsigned int, unsigned int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x1c): undefined reference to `nRF905::restoreConfigRegisters(unsigned char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x20): undefined reference to `nRF905::decodeConfigRegisters()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x24): undefined reference to `nRF905::writeConfigRegisters()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x28): undefined reference to `nRF905::writeTxPayload(unsigned char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x2c): undefined reference to `nRF905::setTxAddress(int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o:(.text._Z9readNVRAMv+0x30): undefined reference to `nRF905::writeTxAddress()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\nRF905API\nvram.cpp.o: in function `readNVRAM()':
C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:11: undefined reference to `Board::ReadNVRAM(unsigned char*, unsigned int, unsigned int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:12: undefined reference to `nRF905::setModeIdle()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:15: undefined reference to `nRF905::restoreConfigRegisters(unsigned char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:15: undefined reference to `nRF905::decodeConfigRegisters()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:17: undefined reference to `nRF905::writeConfigRegisters()'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:18: undefined reference to `nRF905::writeTxPayload(unsigned char const*)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:19: undefined reference to `nRF905::setTxAddress(int)'
c:/users/remco/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\remco\Documents\Arduino\libraries\nRF905API/nvram.cpp:20: undefined reference to `nRF905::writeTxAddress()'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
`

**Comment by arjan-s** [comment]
I think this project is dead, as the owner hasn't replied or committed for a long time. Since you referenced ESPHome, you could take a look here for a newer ESPHome-based alternative to this project: https://github.com/Sanderhuisman/ESPHome-Zehnder-RF

**Comment by remb0** [comment]
thanks!
