### ISSUE TITLE
Unable to pair ComfoAir E300 RF

### ISSUE THREAD

**Issue by cthulu** [eelcohn/nRF905-API#30]
Hi, I am using Lolin32 Lite with nrf905 and I seem to be unable to pair with ComfoAir E300 RF:

```
15:09:41.379 > Fan discover step 3: link
15:09:41.380 > Debug: My ID is 0x2c. Searching...
15:09:41.482 > writeConfigRegisters 00:76:2E:44:10:10:A5:5A:5A:A5:DB:
15:09:41.682 > Starting transmission 4 3 2 1 - done.
15:09:41.818 > Data received
15:09:41.892 > Data received
15:09:42.696 > 00:00:01:49:66:06:04:2A:A8:C2:20:00:00:00:00:00:discover: Found unit type 0x01 with ID 0x49 on network 0x20C2A82A
15:09:42.797 > writeConfigRegisters 00:76:2E:44:10:10:2A:A8:C2:20:DB:
15:09:42.998 > 01:49:03:2C:FA:04:04:2A:A8:C2:20:00:00:00:00:00:Starting transmission 4 3 2 1 - done.
15:09:43.515 > Starting transmission 4 3 2 1 - done.
15:09:44.031 > Starting transmission 4 3 2 1 - done.
15:09:44.548 > Starting transmission 4 3 2 1 - done.
15:09:45.063 > Starting transmission 4 3 2 1 - done.
15:09:45.579 > Starting transmission 4 3 2 1 - done.
15:09:45.614 > Data received
15:09:45.648 > Data received
15:09:45.713 > Data received
15:09:46.595 > Debug: Received unknown frame type 0x4 from ID 0x2c on network 0x20c2a82a
15:09:46.602 > Debug: Received unknown frame type 0x4 from ID 0x2c on network 0x20c2a82a
15:09:46.606 > Debug: Received unknown frame type 0x4 from ID 0x2c on network 0x20c2a82a
15:09:46.615 > Debug: no networks found
```

Not sure whether this is related to NRF905 issue, but it looks like it can "receive" some data (based on the second output).

**Comment by cthulu** [comment]
I was able to get this working via ESPHome and a workaround provided: https://github.com/Sanderhuisman/ESPHome-Zehnder-RF/issues/6
I am not able to read the status of the fan but it's okay enough for my use case.

**Comment by eelcohn** [comment]
I've updated the code to support the ComfoAir E300 RF. If anyone has the same device, I'd be interested if it works.

**Comment by rvk01** [comment]
@eelcohn I have a Zehnder E300. And I already used the old code from a month ago and it worked fine. What did you change? I did need to put the wemos/nrf905 right on top of the Zehnder to get a signal. Edit: I already see... Just the FAN_FRAME_04. Not sure why this wasn't an issue for me.
